name: Sanity checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm ]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Rust Cache save/restore
      uses: Swatinem/rust-cache@v2.7.5
      with:
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - name: Run rustfmt
      run: cargo fmt -- --check
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
